const BANQUE_DE_MOTS = [
    { abreviation: "lavrt", complet: "La vérité" },
    { abreviation: "jpp", complet: "Je ne peux pas" },
    { abreviation: "jsp", complet: "Je ne sais pas" },
    { abreviation: "askip", complet: "À ce qu'il paraît" },
    { abreviation: "ttsa", complet: "Tout ça" },
    { abreviation: "bv", complet: "Bien vu" },
    { abreviation: "clm", complet: "Calme / Au calme" },
    { abreviation: "frr", complet: "Frère" },
    { abreviation: "mdr", complet: "Mort de rire" },
    { abreviation: "cc cv", complet: "Coucou ca va" },
    { abreviation: "slt", complet: "Salut" },
    { abreviation: "ptn", complet: "Putain" },
    { abreviation: "tfq", complet: "Tu fais quoi" },
    { abreviation: "vfq", complet: "Vous faites quoi" },
    { abreviation: "t gnt", complet: "Tu est gênant" },
    { abreviation: "flm", complet: "Flemme" },
    { abreviation: "r", complet: "Rien" },
    { abreviation: "tw", complet: "Toi" },
    { abreviation: "koi/qwa", complet: "Quoi" },
    { abreviation: "dr", complet: "De rien" },
    { abreviation: "oe", complet: "Ouais" },
    { abreviation: "mrc", complet: "Merci" },
    { abreviation: "pk", complet: "Pourquoi" },
    { abreviation: "clc", complet: "Casse les couilles" },
    { abreviation: "avk/avc", complet: "Avec" },
    { abreviation: "jtm", complet: "Je t'aime" },
    { abreviation: "tt.e.s", complet: "Tout.e.s" },
    { abreviation: "ts", complet: "Tous" },
    { abreviation: "bcp", complet: "Beaucoup" },
    { abreviation: "pdt", complet: "Pendant" },
    { abreviation: "vs", complet: "Vous" },
    { abreviation: "auj", complet: "Aujourd'hui" },
    { abreviation: "avt", complet: "Avant" },
    { abreviation: "ds", complet: "Dans" },
    { abreviation: "lgtps", complet: "Longtemps" },
    { abreviation: "jms", complet: "Jamais" },
    { abreviation: "js", complet: "Je sais" },
    { abreviation: "vrm", complet: "Vraiment" }
];